### ISSUE TITLE
[send tab] can only send XRP, can't select other currency to send out.

### ISSUE THREAD

**Issue by yxxyun** [ripple/ripple-client-desktop#116]
maybe a bug?

**Comment by MatthewPhinney** [comment]
<img width="1018" alt="paths" src="https://cloud.githubusercontent.com/assets/4961057/9823089/079b8c68-5879-11e5-9fe1-7f08882e8bbb.png">

**Comment by yxxyun** [comment]
What should I do if I just want send 100USD? I need calculate XRP first?

**Comment by yxxyun** [comment]
![20150912115109](https://cloud.githubusercontent.com/assets/107192/9829744/1312d6e2-5945-11e5-9e32-fde3d7c95e7b.png)
![20150912115143](https://cloud.githubusercontent.com/assets/107192/9829745/13ffbfde-5945-11e5-8899-cf12b7f30438.png)
I had re-checked, send to the same address,the old version can select currency to send out, but the latest version can only send xrp.

**Comment by vhpoet** [comment]
@yxxyun this screen should only appear when you're trying to send money to an unfunded account. Can you confirm that the recipient is funded? if yes, then this is probably a bug that we need to look at.

**Comment by yxxyun** [comment]
Yes, the recipient is funded and have multiple trust lines.

**Comment by vhpoet** [comment]
@yxxyun thanks for the info, will look at this!

**Comment by mrajvanshy** [comment]
@yxxyun this issue was fixed with a recent PR. Let us know if you have any other questions!
