### ISSUE TITLE
can't add trustline at osx64 app

### ISSUE THREAD

**Issue by TOMOAKI12345** [ripple/ripple-client-desktop#177]

**Comment by TOMOAKI12345** [comment]
with the message of Accound doesn't meet minimum XRP reserve
![ripple-client-trustline-failed](https://cloud.githubusercontent.com/assets/2216012/10262133/39703598-69f6-11e5-8405-8e583e97a28e.png)
![rippleclient-trustline](https://cloud.githubusercontent.com/assets/2216012/10262134/3970f8d4-69f6-11e5-9e1d-4e0b6b29b9c9.png)

**Comment by MatthewPhinney** [comment]
Please include the version of the client you are using.

**Comment by TOMOAKI12345** [comment]
@MatthewPhinney thank you for response, this version is 1.2.1

**Comment by MatthewPhinney** [comment]
Try rebuilding the app with the latest source code.

**Comment by TOMOAKI12345** [comment]
@MatthewPhinney  always loading mark, develop branch, and master branch

**Comment by TOMOAKI12345** [comment]
the error message is the same, the latest source code means develop ranch ?

**Comment by stevenzeiler** [comment]
What is your XRP balance? Each trust line requires 5 XRP reserve in addition to the minimum account reserve.

**Comment by TOMOAKI12345** [comment]
@stevenzeiler more than  500 XRP on the account using RIpple-client.
