### ISSUE TITLE
downloadable ripple client fails to start (libudev.so.0)

### ISSUE THREAD

**Issue by vhpoet** [ripple/ripple-client-desktop#25]
https://github.com/ripple/ripple-client/issues/1484

**Comment by eode** [comment]
Specifically, change to the 

```
cd RippleClient
ln -s /lib/x86_64-linux-gnu/libudev.so.1 libudev.so.0
```
Then, make a script file in the RippleClient folder called RippleClient.sh:
```
#! /bin/bash

location=$(dirname $0)

LD_LIBRARY_PATH=$location $location/RippleClient
```
Finally, make RippleClient.sh executable.

This links the library locally, and uses it when starting RippleClient.  Major version increases usually indicate (at least partially) incompatible API changes, and you don't want programs expecting libudev.so.0 to get libudev.so.1, generally speaking.

It's possible (as it appears in RippleClient's case) that it won't cause issues, but it's also possible that it will cause issues, and those issues may not be very easy to trace.  This limits those issues (if any) to RippleClient.

**Comment by vhpoet** [comment]
Fixed in the latest version.

**Comment by eode** [comment]
Thanks.
