### ISSUE TITLE
SOCKS proxy confused for HTTPS proxy

### ISSUE THREAD

**Issue by financehoncho** [ripple/ripple-client-desktop#31]
I have HTTP, HTTPS and SOCKS proxies configured on my Ubuntu 14.04 (using dconf-editor). The HTTP and HTTPS proxies are the same machine/port, the SOCKS proxy is different one.

All this setup works well with browsers and various applications using the different proxies as they should.

Now RippleClient (fresh download dated Jan 13) is offline all the time and in Wireshark I can see it is sending HTTP CONNECT requests to the SOCKS proxy. Is that supposed to happen? I think there is a SOCKS <-> HTTPS proxy confusion.

**Comment by financehoncho** [comment]
In fact after removing the SOCKS configuration from Ubuntu, the client connects just fine.

**Comment by financehoncho** [comment]
upgrading node-webkit to 0.11.6 fixes this, howver introduces other problems. you need to copy chromium's icudtl.dat into the same directory that the executable is in.

**Comment by vhpoet** [comment]
@financehoncho please check it with the latest version and let me know if it's still an issue.

**Comment by financehoncho** [comment]
@vhpoet all fixed, my socks proxy says THANKS!

**Comment by vhpoet** [comment]
yay!
