### ISSUE TITLE
client not connecting

### ISSUE THREAD

**Issue by financehoncho** [ripple/ripple-client-desktop#39]
I compiled the client. The windows version starts but has a blank screen saying "Connecting to Ripple network", then nothing happens. According to Wireshark it isn't attempting any network connections.

**Comment by FredericHeem** [comment]
Same problem here on mac and linux.

**Comment by xavier83** [comment]
any solution yet?

**Comment by vhpoet** [comment]
@financehoncho can you please check it again with the latest changes?

**Comment by financehoncho** [comment]
@vhpoet getting an error about bootstrap.less not being found when building. could be a problem of my setup as nodejs isn't my hometurf. give me another 24h.

**Comment by financehoncho** [comment]
@vhpoet looks like deps/bootstrap/less/bootstrap.less should exist but doesn't. forgot to add before commit? :)

**Comment by vhpoet** [comment]
@financehoncho did you run `bower install`? sorry forgot to put in the instructions. Let me know if it works, I'll add it in gulp.

**Comment by financehoncho** [comment]
@vhpoet bower, of course! all works now, brilliant, thank you very much.

**Comment by vhpoet** [comment]
Thanks for reporting @financehoncho!
